# Generated by Django 4.1 on 2023-06-03 22:52

import api.models
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(upload_to=api.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg'))])),
                ('expiry', models.IntegerField(blank=True, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('expiry_date_time', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('thumbnail_heights', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('include_original_image', models.BooleanField(default=False)),
                ('expiring_link', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to='api.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('thumbnail_image', models.ImageField(upload_to=api.models.user_directory_path)),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='api.imageupload')),
            ],
        ),
    ]
